name: Staging Workflow

on: push

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v7

            - name: ssh setup
              run: |
                  mkdir -p ~/.ssh
                  echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/mein_schlüssel
                  chmod 600 ~/.ssh/mein_schlüssel
                  ssh-keyscan -H ${{secrets.EC2_IP_STAGING}} >> ~/.ssh/known_hosts
              
            - name: install nginx on ec2
              run: |
                  ssh -i ~/.ssh/mein_schlüssel ubuntu@${{secrets.EC2_IP_STAGING}} "sudo apt update && sudo apt install nginx -y"

            - name: deploy website
              run: |
                scp -i ~/.ssh/mein_schlüssel index.html ubuntu@${{secrets.EC2_IP_STAGING}}:/home/ubuntu/index.html
                scp -i ~/.ssh/mein_schlüssel -r images ubuntu@${{secrets.EC2_IP_STAGING}}:/home/ubuntu/images
                ssh -i ~/.ssh/mein_schlüssel ubuntu@${{secrets.EC2_IP_STAGING}} "sudo cp /home/ubuntu/index.html /var/www/html/index.html && sudo cp -r /home/ubuntu/images /var/www/html/images"

            - name: Chuck Norris Witz senden
              if: success()
              run: |
                  JOKE=$(curl -s https://api.chucknorris.io/jokes/random | jq -r '.value')
                  PAYLOAD=$(jq -n --arg content "$JOKE" '{content: $content}')
                  curl -X POST -H 'Content-type: application/json' \
                    --data "$PAYLOAD" \
                    "${{ secrets.DISCORD_WEBHOOK }}"